apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-rolebinding-pod-management
  namespace: jenkins-ns
subjects:
- kind: ServiceAccount
  name: jenkins-sa
  namespace: jenkins-ns
roleRef:
  kind: Role
  name: jenkins-role-pod-management
  apiGroup: rbac.authorization.k8s.io

