apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-rolebinding-app-deployment
  namespace: app-ns
subjects:
- kind: ServiceAccount
  name: jenkins-sa
  namespace: jenkins-ns   
roleRef:
  kind: Role
  name: jenkins-role-app-deployment
  apiGroup: rbac.authorization.k8s.io

